name: Get convert_dict binary

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        options:
        - ubuntu-20.04
        - macos-11
        - windows-2019

jobs:
  build-linux:

    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
